name: Deploy to prod

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ssh to prod and run release script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST_IP }}
          username: ${{ secrets.PROD_APP_USER }}
          key: ${{ secrets.PROD_APP_USER_KEY }}
          script: |
            /bin/bash
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
            cd ~/src \
            && git pull \
            && source ~/.asdf/asdf.sh \
            && bash scripts/release.sh

      - name: Restart app service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST_IP }}
          username: ${{ secrets.PROD_HOST_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            sudo service restbench restart